apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3-tier-app
  namespace: argocd
spec:
  project: default
  source:
    # 1. Point to GitHub repository
    repoURL: https://github.com/wegoagain-dev/3-tier-eks.git
    # 2. The branch to watch
    targetRevision: main
    # 3. Point to the folder containing Kubernetes manifests
    path: k8s

  destination:
    # 4. Deploy to the same cluster ArgoCD is running in
    server: https://kubernetes.default.svc
    # 5. The namespace where app should live
    namespace: 3-tier-app-eks

  # 6. Sync Policy (The "Magic")
  syncPolicy:
    automated:
      prune: true # Delete resources in K8s if they are removed from Git
      selfHeal: true # Fix resources in K8s if someone manually changes them
    syncOptions:
      - CreateNamespace=false # Do not create the namespace, it already exists
