# kind create cluster --name three-tier --config kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # The Brain: Runs API Server, Etcd, Scheduler
  - role: control-plane
  # The Workers: Where your actual React/Flask apps will live
  - role: worker
  - role: worker
