apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: 3-tier-app-eks
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  # Auto-delete job 5 minutes after finishing | try 3 times on failure
  ttlSecondsAfterFinished: 300
  backoffLimit: 3

  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z -v -w30 $RDS_ENDPOINT 5432; do echo "Waiting for DB..."; sleep 2; done;',
            ]
          env:
            - name: RDS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rds-endpoint-secret
                  key: RDS_ENDPOINT
      containers:
        - name: migration
          image: 373317459404.dkr.ecr.eu-west-2.amazonaws.com/3-tier-eks-backend:ad4da6799e6eaae0f3afdf76610854cbdb41e2c8
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "./migrate.sh"]

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      restartPolicy: Never
      activeDeadlineSeconds: 300
