apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: 3-tier-app-eks
  annotations:
    # Run as PostSync hook - executes after all other resources are synced
    # Deletes after success so it doesn't keep recreating
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  # try 3 times on failure
  backoffLimit: 3

  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z -v -w30 $RDS_ENDPOINT 5432; do echo "Waiting for DB..."; sleep 2; done;',
            ]
          env:
            - name: RDS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rds-endpoint-secret
                  key: RDS_ENDPOINT
      containers:
        - name: migration
          image: 373317459404.dkr.ecr.eu-west-2.amazonaws.com/3-tier-eks-backend:5a8149e5f4b1a99172d831dad6b980ca3e9656f2
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "./migrate.sh"]

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      restartPolicy: Never
      activeDeadlineSeconds: 300
