name: Devops Quiz CI/CD (EKS + ArgoCD)
# see github actions workflow like your own computer that is doing steps to what you want to happen
# the steps insted of writing scripts, we can find it in Github Marketplace
on:
  push:
    branches: [main]
  workflow_dispatch: # for manual triggering

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY_FRONTEND: 3-tier-eks-frontend
  ECR_REPOSITORY_BACKEND: 3-tier-eks-backend
  IAM_ROLE_ARN: arn:aws:iam::373317459404:role/GitHubActionsECR

permissions:
  id-token: write # Required for requesting the OIDC JWT Token
  contents: write # Required for committing the new image tag to the repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # frontend image build
      - name: Build frontend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # gets my account id on aws
          IMAGE_TAG: ${{ github.sha }} # needed for argocd and unique name tagging
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend

      - name: Run Trivy vulnerability scanner (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          format: "table"
          exit-code: "1" # This fails the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Push Frontend image to ECR
        if: success() # Only runs if the Trivy scan above passed
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG

      - name: Build backend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # gets my account id on aws
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend

      - name: Run Trivy vulnerability scanner (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
          format: "table"
          exit-code: "1" # This fails the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Push Backend image to ECR
        if: success() # Only runs if the Trivy scan above passed
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG

      # --- GITOPS UPDATE (The "Deployment" Step) --- (revise)
      - name: Update Kubernetes Manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # This updates the 'image:' line in YAML files to the new tag

          # Update Frontend Manifest
          sed -i "s|image: .*$ECR_REPOSITORY_FRONTEND:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG|g" k8s/frontend.yaml

          # Update Backend Manifest
          sed -i "s|image: .*$ECR_REPOSITORY_BACKEND:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG|g" k8s/backend.yaml

          # Update Migration Job Manifest
          sed -i "s|image: .*$ECR_REPOSITORY_BACKEND:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG|g" k8s/migration_job.yaml

          # Check if there are changes
          if [[ `git status --porcelain` ]]; then
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add k8s/frontend.yaml k8s/backend.yaml k8s/migration_job.yaml
            git commit -m "Update image tags to $IMAGE_TAG"
            git push
          else
            echo "No changes to manifests"
          fi
